apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default-trainee
  name: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: default-trainee
subjects:
- kind: User
  name: suresh
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io